### ISSUE TITLE
Samples both in pre-PACS.xlsx and PACS.xlsx

### ISSUE THREAD

**Issue by choisy** [ecomore2/pacs#10]
Somphavanh: sample IDs from **2997** to **3718** are both in the `pre-PACS.xlsx` and the `PACS.xlsx` files. For these IDs, which of these 2 files do you recommend I should consider?
Thanks, Marc.

**Comment by somphavanh** [comment]
please use the pre-pacs ID

**Comment by choisy** [comment]
Do you mean that whenever, for a given sample, there is data both in `pre-PACS.xlsx` and `PACS.xlsx`, I should always prefer data coming from `pre-PACS.xlsx` over data coming from `PACS.xlsx`?

**Comment by somphavanh** [comment]
yes
