### ISSUE TITLE
No ID 4756 in PACS data set

### ISSUE THREAD

**Issue by choisy** [ecomore2/pacs#20]
Somphavanh: the PACS data set (`raw_data/IPL PACS/PACS.xlsx`) does not have ID `4756` whereas this ID is present in the GPS data set (`raw_data/GPS/all main data.xls`). Can you please check what is going on here?
Thanks, Marc.

**Comment by somphavanh** [comment]
when the technician entered the information, they wrote ID:06-4756 , i have already changed it and put on the dropbox with the file name  4576-2018-9-27.

**Comment by somphavanh** [comment]
ok

**Comment by choisy** [comment]
Thanks. Please tell me when it's done.

**Comment by somphavanh** [comment]
already finish for ID 4756

**Comment by choisy** [comment]
Thanks!
