### ISSUE TITLE
Updating the PACS file

### ISSUE THREAD

**Issue by choisy** [ecomore2/pacs#21]
Somphavanh: would it be possible to update the PACS file once a week (for example on Mondays or Fridays) but putting a new dated version of the excel file in the `cleaned_data` directory?
Thanks, Marc.

**Comment by somphavanh** [comment]
ok , i will update every monday

**Comment by somphavanh** [comment]
ok

**Comment by choisy** [comment]
Somphavanh: please don't forget to update the PACS file.
Thanks, Marc.

**Comment by somphavanh** [comment]
i have already added the upate the PACS file . please find at the file ID 7464-8292_2018-10-02

**Comment by choisy** [comment]
Got it! Thanks, works perfectly well!
Marc.

**Comment by somphavanh** [comment]
i have already updated the PACS file. please find it at the file ID 8293-8400_2018-10-08.

**Comment by choisy** [comment]
Amazing! Thanks Somphavanh.
How about GPS? Is the IPL server used at all? If not, what is the reason and can we fix it?
Any other GPS locations collected by IPL staff?
Thanks, Marc.

**Comment by somphavanh** [comment]
we got 5 more  GPS in the IPL server, we still have some problem , if  the mobile of patient or district staffs have the old version , they could not send GPS directly to the IPL server. so i have to discuss this problem with gerome. presently , the IPL staff don't collect GPS location because we don't have vehicle.

**Comment by choisy** [comment]
OK, thanks, please keep posted on GPS progress.

**Comment by somphavanh** [comment]
for 20 GPS that we have to verify , i just got 3  and i have already added in the dropbox.

**Comment by choisy** [comment]
Nice! Thanks a lot for that!

**Comment by somphavanh** [comment]
today , i have already added the updated pacs
